// <auto-generated />
using GameLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GameLibrary.Models.Friend", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FriendId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "FriendId");

                    b.HasIndex("FriendId");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FriendId = 2
                        });
                });

            modelBuilder.Entity("GameLibrary.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ReleaseYear = 2015,
                            Title = "Wiedźmin 3"
                        },
                        new
                        {
                            Id = 2,
                            ReleaseYear = 2011,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 3,
                            ReleaseYear = 2020,
                            Title = "Cyberpunk 2077"
                        });
                });

            modelBuilder.Entity("GameLibrary.Models.GameTag", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GameTags");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            TagId = 1
                        },
                        new
                        {
                            GameId = 1,
                            TagId = 4
                        },
                        new
                        {
                            GameId = 2,
                            TagId = 3
                        },
                        new
                        {
                            GameId = 3,
                            TagId = 1
                        },
                        new
                        {
                            GameId = 3,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("GameLibrary.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan@example.com",
                            Nick = "Jan"
                        },
                        new
                        {
                            Id = 2,
                            Email = "anna@example.com",
                            Nick = "Anna"
                        });
                });

            modelBuilder.Entity("GameLibrary.Models.PlayerGame", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerGames");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            GameId = 1,
                            HoursPlayed = 120
                        },
                        new
                        {
                            PlayerId = 1,
                            GameId = 2,
                            HoursPlayed = 50
                        },
                        new
                        {
                            PlayerId = 2,
                            GameId = 1,
                            HoursPlayed = 80
                        });
                });

            modelBuilder.Entity("GameLibrary.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FPS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "OpenWorld"
                        });
                });

            modelBuilder.Entity("GameLibrary.Models.Friend", b =>
                {
                    b.HasOne("GameLibrary.Models.Player", "FriendPlayer")
                        .WithMany()
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameLibrary.Models.Player", "Player")
                        .WithMany("Friends")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FriendPlayer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameLibrary.Models.GameTag", b =>
                {
                    b.HasOne("GameLibrary.Models.Game", "Game")
                        .WithMany("GameTags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLibrary.Models.Tag", "Tag")
                        .WithMany("GameTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GameLibrary.Models.PlayerGame", b =>
                {
                    b.HasOne("GameLibrary.Models.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameLibrary.Models.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameLibrary.Models.Game", b =>
                {
                    b.Navigation("GameTags");

                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("GameLibrary.Models.Player", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("GameLibrary.Models.Tag", b =>
                {
                    b.Navigation("GameTags");
                });
#pragma warning restore 612, 618
        }
    }
}
